
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'jaffle_shop'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'jaffle_shop'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds", "jaffle-data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  truncate_timespan_to: "{{ current_timestamp() }}"
  "dbt_date:time_zone": "America/Chicago"  


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
seeds:
  +database: EXP_WORKSPACE_DB
  +schema: seed_data

models:
  marts:
    +database: EXP_ANALYTICS_DB
    +materialized: table
    core:
      materialized: table
      +schema: core_learning
    metrics:
      materialized: table
      +schema: metrics_learning
    growth_accounting:
      materialized: table
      +schema: activity_schema_learning
  staging:
    +database: EXP_WORKSPACE_DB
    +materialized: view
    
    jaffle_shop:
      materialzed: view
    # Applies to all files under models/example/
      +schema: jaffle_shop
    stripe:
      materialzed: view
    # Applies to all files under models/example/
      +schema: stripe
    activity_schema:
      +schema: activity_schema

  intermediate: 
    +database: EXP_WORKSPACE_DB
    +materialized: view
  
